//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iMon.XBMC.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string XbmcIp {
            get {
                return ((string)(this["XbmcIp"]));
            }
            set {
                this["XbmcIp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8080")]
        public int XbmcPort {
            get {
                return ((int)(this["XbmcPort"]));
            }
            set {
                this["XbmcPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("xbmc")]
        public string XbmcUsername {
            get {
                return ((string)(this["XbmcUsername"]));
            }
            set {
                this["XbmcUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string XbmcPassword {
            get {
                return ((string)(this["XbmcPassword"]));
            }
            set {
                this["XbmcPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GeneralStartupAuto {
            get {
                return ((bool)(this["GeneralStartupAuto"]));
            }
            set {
                this["GeneralStartupAuto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GeneralStartupConnect {
            get {
                return ((bool)(this["GeneralStartupConnect"]));
            }
            set {
                this["GeneralStartupConnect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GeneralTrayEnabled {
            get {
                return ((bool)(this["GeneralTrayEnabled"]));
            }
            set {
                this["GeneralTrayEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GeneralTrayStartMinimized {
            get {
                return ((bool)(this["GeneralTrayStartMinimized"]));
            }
            set {
                this["GeneralTrayStartMinimized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int XbmcConnectionInterval {
            get {
                return ((int)(this["XbmcConnectionInterval"]));
            }
            set {
                this["XbmcConnectionInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GeneralTrayHideOnClose {
            get {
                return ((bool)(this["GeneralTrayHideOnClose"]));
            }
            set {
                this["GeneralTrayHideOnClose"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GeneralTrayHideOnMinimize {
            get {
                return ((bool)(this["GeneralTrayHideOnMinimize"]));
            }
            set {
                this["GeneralTrayHideOnMinimize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ImonAutoInitialize {
            get {
                return ((bool)(this["ImonAutoInitialize"]));
            }
            set {
                this["ImonAutoInitialize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ImonUninitializeOnError {
            get {
                return ((bool)(this["ImonUninitializeOnError"]));
            }
            set {
                this["ImonUninitializeOnError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool XbmcIdleStaticTextEnable {
            get {
                return ((bool)(this["XbmcIdleStaticTextEnable"]));
            }
            set {
                this["XbmcIdleStaticTextEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("XBMC")]
        public string XbmcIdleStaticText {
            get {
                return ((string)(this["XbmcIdleStaticText"]));
            }
            set {
                this["XbmcIdleStaticText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int ImonLcdScrollingDelay {
            get {
                return ((int)(this["ImonLcdScrollingDelay"]));
            }
            set {
                this["ImonLcdScrollingDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int XbmcGeneralUpdateInterval {
            get {
                return ((int)(this["XbmcGeneralUpdateInterval"]));
            }
            set {
                this["XbmcGeneralUpdateInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ImonSoundSystemEnable {
            get {
                return ((bool)(this["ImonSoundSystemEnable"]));
            }
            set {
                this["ImonSoundSystemEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ImonSoundSystem {
            get {
                return ((int)(this["ImonSoundSystem"]));
            }
            set {
                this["ImonSoundSystem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ImonSoundSystemSPDIF {
            get {
                return ((bool)(this["ImonSoundSystemSPDIF"]));
            }
            set {
                this["ImonSoundSystemSPDIF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XbmcGeneralShowVolume {
            get {
                return ((bool)(this["XbmcGeneralShowVolume"]));
            }
            set {
                this["XbmcGeneralShowVolume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GeneralDebugEnable {
            get {
                return ((bool)(this["GeneralDebugEnable"]));
            }
            set {
                this["GeneralDebugEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XbmcControlModeEnable {
            get {
                return ((bool)(this["XbmcControlModeEnable"]));
            }
            set {
                this["XbmcControlModeEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XbmcControlModeDisableDuringPlayback {
            get {
                return ((bool)(this["XbmcControlModeDisableDuringPlayback"]));
            }
            set {
                this["XbmcControlModeDisableDuringPlayback"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XbmcControlModeRemoveBrackets {
            get {
                return ((bool)(this["XbmcControlModeRemoveBrackets"]));
            }
            set {
                this["XbmcControlModeRemoveBrackets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XbmcControlModeDisplayWindowName {
            get {
                return ((bool)(this["XbmcControlModeDisplayWindowName"]));
            }
            set {
                this["XbmcControlModeDisplayWindowName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool XbmcIconsPlaybackProgress {
            get {
                return ((bool)(this["XbmcIconsPlaybackProgress"]));
            }
            set {
                this["XbmcIconsPlaybackProgress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool XbmcIconsPlaybackMediaType {
            get {
                return ((bool)(this["XbmcIconsPlaybackMediaType"]));
            }
            set {
                this["XbmcIconsPlaybackMediaType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool XbmcIconsPlaybackVideoCodecs {
            get {
                return ((bool)(this["XbmcIconsPlaybackVideoCodecs"]));
            }
            set {
                this["XbmcIconsPlaybackVideoCodecs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool XbmcIconsPlaybackAudioCodecs {
            get {
                return ((bool)(this["XbmcIconsPlaybackAudioCodecs"]));
            }
            set {
                this["XbmcIconsPlaybackAudioCodecs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"DivX\":[\"DivX\"],\"XviD\":[\"XviD\"],\"MPG\":[\"MPG\",\"MP4\"],\"WMV\":[\"WMV\"]}")]
        public string XbmcIconsPlaybackVideoCodecsMappings {
            get {
                return ((string)(this["XbmcIconsPlaybackVideoCodecsMappings"]));
            }
            set {
                this["XbmcIconsPlaybackVideoCodecsMappings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"AC3\":[\"AC3\"],\"DTS\":[\"DTS\", \"DCA\"],\"MPG\":[\"MP1\",\"MP2\"],\"WMA\":[\"WMA\"], \"MP3\":[\"MP" +
            "3\"], \"OGG\":[\"OGG\"], \"WAV\":[\"WAV\"]}")]
        public string XbmcIconsPlaybackAudioCodecsMappings {
            get {
                return ((string)(this["XbmcIconsPlaybackAudioCodecsMappings"]));
            }
            set {
                this["XbmcIconsPlaybackAudioCodecsMappings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GeneralTrayDisableBalloonTips {
            get {
                return ((bool)(this["GeneralTrayDisableBalloonTips"]));
            }
            set {
                this["GeneralTrayDisableBalloonTips"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool XbmcMovieSingleTextEnable {
            get {
                return ((bool)(this["XbmcMovieSingleTextEnable"]));
            }
            set {
                this["XbmcMovieSingleTextEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%title%")]
        public string XbmcMovieSingleText {
            get {
                return ((string)(this["XbmcMovieSingleText"]));
            }
            set {
                this["XbmcMovieSingleText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool XbmcTvShowTvMediaTypeIcon {
            get {
                return ((bool)(this["XbmcTvShowTvMediaTypeIcon"]));
            }
            set {
                this["XbmcTvShowTvMediaTypeIcon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XbmcTvShowTvHdtvIcon {
            get {
                return ((bool)(this["XbmcTvShowTvHdtvIcon"]));
            }
            set {
                this["XbmcTvShowTvHdtvIcon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%show%: S%season%E%episode% - %title%")]
        public string XbmcTvSingleText {
            get {
                return ((string)(this["XbmcTvSingleText"]));
            }
            set {
                this["XbmcTvSingleText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool XbmcTvSingleTextEnable {
            get {
                return ((bool)(this["XbmcTvSingleTextEnable"]));
            }
            set {
                this["XbmcTvSingleTextEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool XbmcMusicSingleTextEnable {
            get {
                return ((bool)(this["XbmcMusicSingleTextEnable"]));
            }
            set {
                this["XbmcMusicSingleTextEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%artist%: %title%")]
        public string XbmcMusicSingleText {
            get {
                return ((string)(this["XbmcMusicSingleText"]));
            }
            set {
                this["XbmcMusicSingleText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool XbmcMusicVideoSingleTextEnable {
            get {
                return ((bool)(this["XbmcMusicVideoSingleTextEnable"]));
            }
            set {
                this["XbmcMusicVideoSingleTextEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%artist%: %title%")]
        public string XbmcMusicVideoSingleText {
            get {
                return ((string)(this["XbmcMusicVideoSingleText"]));
            }
            set {
                this["XbmcMusicVideoSingleText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool XbmcIconsPlaybackDiscEnable {
            get {
                return ((bool)(this["XbmcIconsPlaybackDiscEnable"]));
            }
            set {
                this["XbmcIconsPlaybackDiscEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool XbmcIconsPlaybackDiscRotate {
            get {
                return ((bool)(this["XbmcIconsPlaybackDiscRotate"]));
            }
            set {
                this["XbmcIconsPlaybackDiscRotate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool XbmcIconsPlaybackDiscBottomCircle {
            get {
                return ((bool)(this["XbmcIconsPlaybackDiscBottomCircle"]));
            }
            set {
                this["XbmcIconsPlaybackDiscBottomCircle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XbmcIdleTimeShowSeconds {
            get {
                return ((bool)(this["XbmcIdleTimeShowSeconds"]));
            }
            set {
                this["XbmcIdleTimeShowSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9090")]
        public int XbmcTcpPort {
            get {
                return ((int)(this["XbmcTcpPort"]));
            }
            set {
                this["XbmcTcpPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PAUSE")]
        public string XbmcOnPauseText {
            get {
                return ((string)(this["XbmcOnPauseText"]));
            }
            set {
                this["XbmcOnPauseText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PLAY")]
        public string XbmcOnPlayText {
            get {
                return ((string)(this["XbmcOnPlayText"]));
            }
            set {
                this["XbmcOnPlayText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("STOP")]
        public string XbmcOnStopText {
            get {
                return ((string)(this["XbmcOnStopText"]));
            }
            set {
                this["XbmcOnStopText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("END")]
        public string XbmcOnEndText {
            get {
                return ((string)(this["XbmcOnEndText"]));
            }
            set {
                this["XbmcOnEndText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int XbmcOnEventTextDelayMS {
            get {
                return ((int)(this["XbmcOnEventTextDelayMS"]));
            }
            set {
                this["XbmcOnEventTextDelayMS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Connected")]
        public string XbmcOnConnectedText {
            get {
                return ((string)(this["XbmcOnConnectedText"]));
            }
            set {
                this["XbmcOnConnectedText"] = value;
            }
        }
    }
}
